### ISSUE TITLE
Plans for decoding?

### ISSUE THREAD

**Issue by ckaran** [buntine/barcoders#18]
I ran across barcoders while searching for open source libraries that could be adapted to scanning barcodes using a smart phone.  Do you have any plans for adding decoding support from images that a phone can take?

**Comment by buntine** [comment]
Sorry for the delay, I didn't see this somehow. No, there is currently no plans to add decoding directly into barcoders. But perhaps as a separate library it would be cool.

**Comment by ckaran** [comment]
@buntine Ah, that's unfortunate.  I was kind of looking at this like [serde](https://crates.io/crates/serde) for barcodes.  But a separate crate that kept in lock-step with barcoders would work too.  Thank you for creating this crate!
