### ISSUE TITLE
Dependency on `image` 0.22 needs updating to 0.23

### ISSUE THREAD

**Issue by timwalls** [buntine/barcoders#21]
barcoders depends on `image` 0.22 (when the `image` feature is enabled).  Unfortunately 0.22 has a security vulnerability (https://rustsec.org/advisories/RUSTSEC-2020-0073), and fails a `cargo audit` (meaning so does `barcoders`.)

The vulnerability is fixed in `image` 0.23.

**Comment by ondrejkolin** [comment]
@buntine Sorry for pinging, I do understand it's a very rude thing to do, but is there a chance for you to merge this pull request? 

I am building a GTK app with your great library and I would like to avoid delivering potential security issue. 

Thanks!

**Comment by matveitolochko** [comment]
see https://github.com/buntine/barcoders/pull/22#issuecomment-2028449494

**Comment by matveitolochko** [comment]
@timwalls Fixed in #31 
This is now safe to close
