### ISSUE TITLE
Invalid EAN13 image generation?

### ISSUE THREAD

**Issue by sergeyshaykhullin** [buntine/barcoders#23]
I have a barcode 2000926398005. I tried to generate an image from it 

Same as example

```rs
let barcode = EAN13::new("2000926398005").unwrap();
let png = Image::png(50);
let encoded = barcode.encode();

let bytes = png.generate(&encoded[..]).unwrap();

let file = File::create(&Path::new("my_barcode.png")).unwrap();
let mut writer = BufWriter::new(file);
writer.write(&bytes[..]).unwrap();
```

Expected image:
![2000926398005](https://user-images.githubusercontent.com/46970457/130353864-7c0d7d4a-5cde-45eb-9fe0-f5cf0c0581ee.jpeg)
Last - 1 fat, 2 thin

Barcoders generated image:
![my_barcode](https://user-images.githubusercontent.com/46970457/130353938-bc54c3e1-0203-48dc-b0a4-a1b7d2a41f4b.png)
Last - 2 fat, 3 thin

Barcoders generated images is not scannable

**Comment by sergeyshaykhullin** [comment]
I tried values from test but...

![image](https://user-images.githubusercontent.com/46970457/130354138-a059f0c0-606d-4ae3-aabc-04ee473215ed.png)

Scanned barcode is not the same/ It has a 9 at the end
![image](https://user-images.githubusercontent.com/46970457/130354151-289633ae-7db0-4dd1-9641-d95003c0418a.png)

**Comment by tscott0** [comment]
I have a similar issue with EAN8 codes. In my experience, dropping the last digit (the checkdigit) provides a workaround.

```rust
let ean = "200092639800";
let barcode = EAN13::new(ean).unwrap();
```

The above code outputs this barcode, which seems to match yours. Scanning it returns 2000926398005 too.

![200092639800](https://user-images.githubusercontent.com/14017974/131998362-6701255c-f032-4aa7-ae97-5c2149f34e5d.png)

**Comment by sergeyshaykhullin** [comment]
Workaround is found. Don't think that providing barcodes without chechdigit is a good idea. Maybe `EAN13::with_check_digit(ean)` needed.

Closing for now
