### ISSUE TITLE
docs: `Code128` documentation and example improvements

### ISSUE THREAD

**Issue by chrisp60** [buntine/barcoders#30]
I feel describing the character sets for `Code128` may help other users deal with issues relating to its API. 

[source](https://en.wikipedia.org/wiki/Code_128#Subtypes)
> 128A (Code Set A) – ASCII characters 00 to 95 (0–9, A–Z and control codes), special characters, and FNC 1–4
> 128B (Code Set B) – ASCII characters 32 to 127 (0–9, A–Z, a–z), special characters, and FNC 1–4
> 128C (Code Set C) – 00–99 (encodes two digits with a single code point) and FNC1

**I would be happy to make a PR with an excerpt added to the docs and possibly a more descriptive error message.**

This is definitely not the responsibility of the library to educate people on the character sets, but also I do not think it would hurt to include.

possibly tangentially related to #20.

**Comment by buntine** [comment]
Thanks, feel free to open a PR for those docs :+1:

**Comment by buntine** [comment]
Merged. Thanks!
