### ISSUE TITLE
When the version 1.0.4 will be publish in crates.io?

### ISSUE THREAD

**Issue by JonRC** [buntine/barcoders#32]
When the version 1.0.4 will be publish in crates.io?

I need compatibility with `image 0.25` package for my project.

**Comment by buntine** [comment]
I'll try get it published within the next day or so.

**Comment by JonRC** [comment]
Thanks, I'm waiting for that.

**Comment by buntine** [comment]
Published v2.0.0 to crates.io

Note that JPEG support has been removed in place of WEBP support for image generation.
