### ISSUE TITLE
Code93 Invalid Character

### ISSUE THREAD

**Issue by matveitolochko** [buntine/barcoders#37]
It appears that in Code93 you aren't able to encode the `]`, although the spec says you can.

I found the issue: https://github.com/buntine/barcoders/blob/eb7ce1d59eeecf242b5437f577b7edba763c812d/src/sym/code93.rs#L64-L65

I will be fixing it in https://github.com/buntine/barcoders/pull/36

**Comment by buntine** [comment]
Thanks! Also fixed in: https://github.com/buntine/barcoders/commit/7f8df633b91d910ac48d802e22e168529b4028a1
