### ISSUE TITLE
UPCA barcodes are generated with an extra digit (UPCA != EAN)

### ISSUE THREAD

**Issue by jayrahdevore** [buntine/barcoders#39]
I've been trying to cross-references differences between the output of this crate and various barcode generators like [this one](https://www.cognex.com/resources/interactive-tools/free-barcode-generator).  This crate seems to encode UPCA codes as EAN13 (UPCA + an extra zero).  While EAN-13 is a superset of UPCA, to my understanding, this relationship isn't symmetrical.  Encoding UPCA as EAN-13 adds an extra '0' that isn't valid UPCA.

**Comment by buntine** [comment]
Closed via #40.

Thanks!
