### ISSUE TITLE
Hosted service

### ISSUE THREAD

**Issue by anowell** [buntine/barcoders#6]
I spotted barcoders on reddit and thought it looked solid, so I quickly hacked together a hosted version of it and hosted it on our startup's platform here:
 [![Algorithmia](https://algorithmia.com/algorithms/anowell/barcoders/badge)](https://algorithmia.com/algorithms/anowell/barcoders)

If you're interested in owning/maintaining it on our platform, I'm happy to help make that happen. Otherwise, I just thought I'd share another way in which your work is being highlighted, and I'll keep an eye out for updates that we can take advantage of. Feel free to close this issue. :-)

**Comment by buntine** [comment]
Thanks. Your platform seems pretty cool. I'll add a link to it on my README. What is involved in me taking over maintenance of it on your platform? I was planning to make some performance updates to the SVG output soon that will impact your hosted version.

**Comment by anowell** [comment]
Thanks. Glad you think the platform seems cool. :blush:

We still lack a feature to directly transfer ownership, so in this case, since the wrapper I wrote was pretty minimal, the easiest approach is to just create a new "algorithm" on the platform, add these 2 dependencies:

```
error-chain = "0.9.0"
barcoders = {version = "0.7.0", features = ["svg"]}
```

then copy the [lib.rs source](https://algorithmia.com/algorithms/anowell/barcoders/edit), hit compile, then publish, and edit the description to your liking. Then let me know, and I'll effectively hide mine and redirect it to yours. It's worth noting, the edit-compile experience for rust in the web editor isn't great (long compiles) so I'd definitely recommend cloning (`https://git.algorithmia.com/git/USERNAME/ALGONAME.git`) for any local development.

**Comment by buntine** [comment]
Ok, thanks. I'll do this soon.
